# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
- name: mysql-root-pass
  literals:
  - password=root
- name: mysql-user-pass
  literals:
  - username=root
  - password=root 
- name: mysql-db-url
  literals:
  - database=db
  - url=jdbc:mysql://todo-app-mysql:3306/db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8
resources:
  - storage.yaml
  - mysql-stack.yaml
  - api.yaml
  - ui.yaml  
