version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '330:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080

  ui:
    build:
      context: ../ui
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - api

volumes:
  my-db:
